/* sounds.h - GENERATED by tools/make_sounds.py; do not edit.
 * Cue ids + the clip/cue tables over the sound bank
 * (assets/sounds/sounds.bin: 16 kHz mono s16, clips back to back).
 * A cue with n_var == 0 is deferred: valid id, plays nothing. */
#ifndef SOUNDS_H
#define SOUNDS_H
#include <stdint.h>

#define SND_RATE 16000
#define SND_BANK_SAMPLES 243672u
#define SND_BANK_BYTES 487344u

enum {
    SND_TAP,
    SND_FEED,
    SND_LIGHT_ON,
    SND_LIGHT_OFF,
    SND_WIPE,
    SND_SNIP,
    SND_CARD_OPEN,
    SND_CARD_CLOSE,
    SND_WHEEL_TICK,
    SND_CONFIRM,
    SND_BUBBLES_LOOP,
    SND_EAT,
    SND_SPOOK,
    SND_INVESTIGATE,
    SND_BUBBLES,
    SND_BEG,
    SND_WELCOME,
    SND_ARRIVAL,
    SND_MILESTONE,
    SND_STAGE_UP,
    SND_SLEEP,
    SND_WAKE,
    SND_ERROR,
    SND_COUNT
};

typedef struct { uint32_t off, len; } snd_clip_t;   /* samples into the bank */
typedef struct {
    const char *name;
    uint8_t  first, n_var;    /* SND_CLIPS[first .. first + n_var) */
    uint8_t  loop;            /* seamless wrap (bubbles_loop) */
    uint16_t gain_q8;         /* playback gain, 256 = 0 dB (gains.csv) */
} snd_cue_t;

#define SND_N_CLIPS 16
extern const snd_clip_t SND_CLIPS[SND_N_CLIPS];
extern const snd_cue_t  SND_CUES[SND_COUNT];

#endif
